### ISSUE TITLE
Delegate does not implement -readerSessionDidBecomeActive: method

### ISSUE THREAD

**Issue by methods-inaz** [1998code/SwiftNFC#4]
Hi,
with version 1.3.0 when I scan a nfc tag I receive on Xcode console the following error:

-[NFCNDEFReaderSession _callbackDidBecomeActive]:220 Delegate does not implement -readerSessionDidBecomeActive: method

the issue seems to be in the empty body of this function:

public func readerSessionDidBecomeActive(_ session: NFCNDEFReaderSession) {
    }

It is possible to solve it?

**Comment by 1998code** [comment]
Hi @methods-inaz, Which Xcode version are you using?

**Comment by 1998code** [comment]
You may reopen this issue if you still need help ♥️
