### ISSUE TITLE
 class "NFFieldNotificationECP2_0" not loaded or does not exist

### ISSUE THREAD

**Issue by navneetcrebos** [1998code/SwiftNFC#5]
I am getting this issue can you please check this : 

<NSXPCConnection: 0x303f9c640> connection to service with pid 60 named com.apple.nfcd.service.corenfc: Exception caught during decoding of received selector didDetectExternalReaderWithNotification:, dropping incoming message.
Exception: Exception while decoding argument 0 (#2 of invocation):
Exception: decodeObjectForKey: class "NFFieldNotificationECP2_0" not loaded or does not exist

**Comment by 1998code** [comment]
Hello @navneetcrebos 
Have you added the capability "Near Field Communication Tag Reading"?

**Comment by navneetcrebos** [comment]
Hey @1998code thanks , 

but it is working now.

**Comment by 1998code** [comment]
Great!
